#!/bin/bash
#projrct : SSLH (Multi Port )


#upgrade 
apt update
apt upgrade
#install sslh
apt-get install sslh

#konfigurasi
wget -O /etc/default/sslh "https://raw.githubusercontent.com/Gugun09/sslh/main/sslh.conf"

#restart Service
service ssh restart
service stunnel4 restart
service openvpn restart
service sslh restart
